fsmviz-simple: highlight node with pending signals
Add signal queue and initial signal handling for nodes

When interactive, use tk.Toplevel() to avoid
    TclError: image "pyimage5" doesn't exist

Fill active nodes for emphasis